# -*- coding: utf-8 -*-
"""codex-s.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gPdmW88mCNbHx8vfs8Wr125t5IjXLLhx
"""

# !pip install pykeen -q

# !pip install -q \
    langchain \
    langchain-community \
    langchain-core \
    langchain-huggingface \
    faiss-cpu \
    sentence-transformers \
    transformers \
    accelerate \
    bitsandbytes

# Commented out IPython magic to ensure Python compatibility.
 !git clone https://github.com/tsafavi/codex
#  %cd codex
 !./extract.sh en  # unzip all KG text in English
 !pip install -r requirements.txt
 !pip install -e .

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from codex.codex import Codex
from pykeen.datasets import Nations
from pykeen.pipeline import pipeline
import pandas as pd
import numpy as np
import torch
import torch.nn.functional as F
from collections import defaultdict

sizes = Codex.SIZES
codes = Codex.CODES

for size in sizes:
    codex = Codex(size=size)

    train, valid, test = [
        codex.split(split) for split in ("train", "valid", "test")]
    triples = codex.triples()

    print(codex.name())

    print(
        " ", len(codex.entities()), "entities /",
        len(codex.relations()), "relations"
    )

    print(
        " ", len(train), "train /",
        len(valid), "validation /",
        len(test), "test"
    )
    print(" ", len(triples), "total triples")

from codex.codex import Codex

codex = Codex(size="s", code="en")

def resolve_triple(row):
    return (
        codex.entity_label(row["head"])      or row["head"],
        codex.relation_label(row["relation"]) or row["relation"],
        codex.entity_label(row["tail"])      or row["tail"],
    )

raw_train = codex.split("train")
raw_test  = codex.split("test")
raw_valid = codex.split("valid")

df_train = pd.DataFrame(
    [resolve_triple(row) for _, row in raw_train.iterrows()],
    columns=["head", "relation", "tail"]
)
df_test = pd.DataFrame(
    [resolve_triple(row) for _, row in raw_test.iterrows()],
    columns=["head", "relation", "tail"]
)
df_valid = pd.DataFrame(
    [resolve_triple(row) for _, row in raw_valid.iterrows()],
    columns=["head", "relation", "tail"]
)
df_all = pd.concat([df_train, df_test], ignore_index=True)

print(f"Train: {len(df_train)}  Valid: {len(df_valid)}  Test: {len(df_test)}")
print(df_train.head(5).to_string(index=False))

def show_neighborhood(entity, graph):
    print(f"\n{'='*50}")
    print(f"Neighborhood of: {entity}")
    print(f"{'='*50}")
    neighbors = graph.get(entity, [])
    print(f"Direct edges: {len(neighbors)}")
    print(f"\n{'Relation':<30} {'Tail':<20}")
    print("-" * 50)
    for relation, tail in sorted(neighbors, key=lambda x: x[0]):
        print(f"{relation:<30} {tail:<20}")

entities_raw  = sorted(codex.entities())
relations_raw = sorted(codex.relations())

entity_to_id   = {e: i for i, e in enumerate(entities_raw)}
relation_to_id = {r: i for i, r in enumerate(relations_raw)}
id_to_entity   = {i: e for e, i in entity_to_id.items()}
id_to_relation = {i: r for r, i in relation_to_id.items()}

# English label → Q/P code (needed by score_hrt lookups)
label_to_entity   = {(codex.entity_label(e)   or e): e for e in entities_raw}
label_to_relation = {(codex.relation_label(r) or r): r for r in relations_raw}

# graph uses English strings directly — no integer conversion needed
def build_graph_from_df(df):
    graph = defaultdict(list)
    for _, row in df.iterrows():
        graph[row["head"]].append((row["relation"], row["tail"]))
    return graph

graph = build_graph_from_df(df_train)

print(f"Entities:    {len(entities_raw)}")
print(f"Relations:   {len(relations_raw)}")
print(f"Graph nodes: {len(graph)}")

# spot check — pick first entity in graph
sample = df_train["head"].iloc[0]
show_neighborhood(sample, graph)

# NEW — graph builds directly from string df, no int conversion needed
def build_graph_from_df(df):
    graph = defaultdict(list)
    for _, row in df.iterrows():
        graph[row["head"]].append((row["relation"], row["tail"]))
    return graph

graph = build_graph_from_df(df_train)
print(f"Graph nodes: {len(graph)}")
print(df_train.head(5).to_string(index=False))

def extract_subgraph(entity, graph, hops=4):
    """
    Pulls all triples within N hops of entity.

    hop=1: only direct edges from entity
    hop=2: direct edges + edges from those neighbors

    This becomes Agent B's local context.
    """
    subgraph = []
    visited  = set()

    def walk(node, depth):
        if depth == 0 or node in visited:
            return
        visited.add(node)
        for relation, tail in graph.get(node, []):
            subgraph.append((node, relation, tail))
            walk(tail, depth - 1)

    walk(entity, hops)
    return subgraph

# now — extract focused subgraph around the query entities
# for probe: (usa, militaryalliance, uk) vs netherlands
def focused_subgraph(entities, graph, hops=1):
    """
    Extracts subgraph around multiple entities.
    Filters to only show triples connecting them.

    This is the ~30 triple context you pass to the LLM.
    """
    all_triples = []
    for entity in entities:
        all_triples.extend(
            extract_subgraph(entity, graph, hops)
        )

    # deduplicate
    seen    = set()
    unique  = []
    for triple in all_triples:
        key = (triple[0], triple[1], triple[2])
        if key not in seen:
            seen.add(key)
            unique.append(triple)

    return unique

import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
torch.cuda.empty_cache()

def get_entity_embeddings(model):
    embs = model.entity_representations[0](
        indices=None
    ).detach().cpu()

    # RotatE uses complex numbers — convert to real magnitude
    if embs.is_complex():
        embs = embs.abs()

    return embs

def similarity_summary(entity, model, k=5):
    embs  = get_entity_embeddings(model)
    e_id  = entity_to_id[entity]
    e_vec = embs[e_id]

    sims  = F.cosine_similarity(
        e_vec.unsqueeze(0), embs
    ).detach().cpu().numpy()

    ranked  = np.argsort(sims)[::-1]
    results = []

    for idx in ranked:
        name = id_to_entity[idx]
        if name == entity:
            continue
        score = sims[idx]

        entity_rels   = set(
            df_train[df_train["tail"] == entity]["relation"]
        )
        neighbor_rels = set(
            df_train[df_train["tail"] == name]["relation"]
        )
        shared = len(entity_rels & neighbor_rels)

        results.append((name, score, shared))
        if len(results) == k:
            break

    parts   = [
        f"{name}(sim={score:.2f}, shared_rels={shared})"
        for name, score, shared in results
    ]
    summary = f"{entity} most similar to: {', '.join(parts)}"

    return summary, results

def hop_classifier(head, tail, graph, target_relation=None):
    """
    If target_relation is specified:
      single = direct edge exists with THAT relation
      multi  = reachable but via different relations
    """
    # check direct edge with matching relation
    for relation, t in graph.get(head, []):
        if t == tail:
            if target_relation is None or relation == target_relation:
                return "single", 1, relation

    # direct edge exists but wrong relation
    direct_wrong = [r for r, t in graph.get(head, []) if t == tail]
    if direct_wrong:
        return "multi", 1.5, f"direct but via {direct_wrong[0]}"

    # check 2-hop
    paths_found = []
    for r1, mid in graph.get(head, []):
        for r2, t2 in graph.get(mid, []):
            if t2 == tail:
                paths_found.append(
                    f"{head}-{r1}->{mid}-{r2}->{tail}"
                )

    if paths_found:
        return "multi", 2, paths_found[0]

    return "none", 99, []

def get_full_ranking_filtered(head, relation, true_tail, model):
    """
    Scores all entities as candidate tails for (head, relation, ?).
    Filters out the head entity itself (self-loop).
    Returns rank of true_tail plus full sorted ranking.
    """
    h_id = entity_to_id[label_to_entity.get(head, head)]
    r_id = relation_to_id[label_to_relation.get(relation, relation)]

    all_scores = []
    for i in range(len(entity_to_id)):
        # skip self-prediction
        if id_to_entity[i] == head:
            continue
        score = model.score_hrt(
            torch.tensor([[h_id, r_id, i]]).to(device)
        ).item()
        all_scores.append((id_to_entity[i], score, i))

    all_scores.sort(key=lambda x: -x[1])

    ranked_entities = [e for e, s, i in all_scores]
    true_rank       = ranked_entities.index(true_tail) + 1
    predicted       = all_scores[0][0]

    return {
        "predicted":       predicted,
        "predicted_score": all_scores[0][1],
        "true_tail":       true_tail,
        "true_score":      next(s for e, s, i in all_scores if e == true_tail),
        "true_rank":       true_rank,
        "full_ranking":    [(e, round(s, 3)) for e, s, i in all_scores],
    }

from pykeen.triples import TriplesFactory

# build PyKEEN factories from English string DataFrames
pykeen_train = TriplesFactory.from_labeled_triples(
    df_train[["head", "relation", "tail"]].values
)
pykeen_test = TriplesFactory.from_labeled_triples(
    df_test[["head", "relation", "tail"]].values,
    entity_to_id=pykeen_train.entity_to_id,
    relation_to_id=pykeen_train.relation_to_id,
)

# resync ID maps to match PyKEEN's internal ordering
entity_to_id   = pykeen_train.entity_to_id
relation_to_id = pykeen_train.relation_to_id
id_to_entity   = {v: k for k, v in entity_to_id.items()}
id_to_relation = {v: k for k, v in relation_to_id.items()}

# label_to_entity/relation now maps English → English (identity, but keeps API consistent)
label_to_entity   = {e: e for e in entity_to_id}
label_to_relation = {r: r for r in relation_to_id}

result = pipeline(
    training=pykeen_train,
    testing=pykeen_test,
    model="RotatE",
    training_kwargs=dict(num_epochs=200),
    random_seed=42,
)
winner_model = result.model

def failure_summary(head, relation, true_tail,
                    predicted_tail, model, df_train):
    # English label → integer ID via label_to_entity map
    h_id = entity_to_id[label_to_entity.get(head, head)]
    r_id = relation_to_id[label_to_relation.get(relation, relation)]
    t_id = entity_to_id[label_to_entity.get(true_tail, true_tail)]
    p_id = entity_to_id[label_to_entity.get(predicted_tail, predicted_tail)]

    score_true = model.score_hrt(
        torch.tensor([[h_id, r_id, t_id]])
    ).item()
    score_pred = model.score_hrt(
        torch.tensor([[h_id, r_id, p_id]])
    ).item()

    # df_train already has English strings so filtering works directly
    true_rels = set(
        df_train[
            (df_train["head"] == head) &
            (df_train["tail"] == true_tail)
        ]["relation"]
    )
    pred_rels = set(
        df_train[
            (df_train["head"] == head) &
            (df_train["tail"] == predicted_tail)
        ]["relation"]
    )

    shared    = true_rels & pred_rels
    only_true = true_rels - pred_rels
    only_pred = pred_rels - true_rels

    # English strings throughout — no resolve_labels() needed anywhere
    summary = (
        f"Model predicted '{predicted_tail}' "
        f"(score={score_pred:.3f}) over '{true_tail}' "
        f"(score={score_true:.3f}). "
        f"Shared relations: {len(shared)}. "
        f"Only '{true_tail}' has: "
        f"{', '.join(only_true) if only_true else 'none'}. "
        f"Only '{predicted_tail}' has: "
        f"{', '.join(only_pred) if only_pred else 'none'}."
    )

    return summary, {
        "score_true": score_true,
        "score_pred": score_pred,
        "shared":     shared,
        "only_true":  only_true,
        "only_pred":  only_pred,
    }

if 'winner_model' not in dir():
    print("Run RotatE training cell first.")
else:
    sample_head  = df_train["head"].iloc[0]
    sample_rel   = df_train[df_train["head"] == sample_head]["relation"].iloc[0]
    sample_tails = df_train[
        (df_train["head"] == sample_head) &
        (df_train["relation"] == sample_rel)
    ]["tail"].tolist()

    probe_true      = sample_tails[0]
    probe_predicted = next(
        e for e in entity_to_id
        if e != sample_head and e != probe_true
    )

    summary_fail, raw_fail = failure_summary(
        head           = sample_head,
        relation       = sample_rel,
        true_tail      = probe_true,
        predicted_tail = probe_predicted,
        model          = winner_model,
        df_train       = df_train,
    )

    print("=== FAILURE SUMMARY ===")
    print(summary_fail)
    print(f"\nOnly true tail has: {sorted(raw_fail['only_true'])}")
    print(f"Only predicted has: {sorted(raw_fail['only_pred'])}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using: {device}")

import json
import numpy as np

def preprocess_all_triples(model, df, split_name, df_reference):
    """
    Runs get_full_ranking_filtered on every triple.
    Stores rank, predicted, score, failure info.
    All splits. Run once. Never again.

    df_reference: training dataframe used for relation analysis
                  pass df_train for CoDEx-S
    """
    records = []
    total   = len(df)
    df      = df.reset_index(drop=True)

    for i, row in df.iterrows():
        head     = row["head"]
        relation = row["relation"]
        tail     = row["tail"]

        if relation not in relation_to_id:
            continue
        if head not in entity_to_id:
            continue
        if tail not in entity_to_id:
            continue

        ranking = get_full_ranking_filtered(
            head, relation, tail, model
        )

        sim_head, _ = similarity_summary(head, model, k=5)
        sim_tail, _ = similarity_summary(tail, model, k=5)

        subgraph = focused_subgraph(
            [head, tail, ranking["predicted"]],
            graph, hops=1
        )

        hop_type, hops, detail = hop_classifier(
            head, tail, graph,
            target_relation=relation
        )

        fail_summary, fail_raw = failure_summary(
            head, relation, tail, ranking["predicted"], model, df_reference
        )

        record = {
            "split":            split_name,
            "head":             head,
            "relation":         relation,
            "tail":             tail,
            "true_rank":        ranking["true_rank"],
            "predicted":        ranking["predicted"],
            "score_true":       ranking["true_score"],
            "score_predicted":  ranking["predicted_score"],
            "top5":             ranking["full_ranking"][:5],
            "hop_type":         hop_type,
            "hop_count":        hops,
            "sim_head":         sim_head,
            "sim_tail":         sim_tail,
            "fail_summary":     fail_summary,
            "subgraph":         subgraph,
            "shared_relations": list(fail_raw["shared"]),
            "only_tail_has":    list(fail_raw["only_true"]),
            "only_pred_has":    list(fail_raw["only_pred"]),
            "hard_failure":     ranking["true_rank"] > 3,
        }

        records.append(record)

        if (i + 1) % 50 == 0:
            print(f"  {split_name}: {i+1}/{total} done")

    return records

if 'result' not in dir():
    print("Run RotatE training cell first.")
else:
    winner_model = result.model
    df_train_run = df_train.sample(n=min(3000, len(df_train)), random_state=42)
    df_test_run  = df_test.sample(n=min(2000,  len(df_test)),  random_state=42)
    print(f"Train available: {len(df_train)}  Test available: {len(df_test)}")

    print("Processing training triples...")
    train_records = preprocess_all_triples(
        winner_model, df_train_run, "train", df_train
    )

    print("\nProcessing test triples...")
    test_records = preprocess_all_triples(
        winner_model, df_test_run, "test", df_train
    )

    all_records = train_records + test_records

    with open("codex_s_preprocessed_train.json", "w") as f:
        json.dump(train_records, f, indent=2)

    with open("codex_s_preprocessed_test.json", "w") as f:
        json.dump(test_records, f, indent=2)

    with open("codex_s_preprocessed_all.json", "w") as f:
        json.dump(all_records, f, indent=2)

    print(f"\nDone.")
    print(f"Train records: {len(train_records)}")
    print(f"Test records:  {len(test_records)}")
    print(f"Total:         {len(all_records)}")

    df_preprocessed = pd.DataFrame(all_records)

    print(f"\nRank distribution (test split):")
    test_df = df_preprocessed[df_preprocessed["split"] == "test"]
    print(test_df["true_rank"].value_counts().sort_index())

    print(f"\nHard failures in test: "
          f"{test_df['hard_failure'].sum()} / {len(test_df)}")

    print(f"\nHop type distribution:")
    print(df_preprocessed["hop_type"].value_counts())

    print(f"\n=== SAMPLE RECORD (first test triple) ===")
    print(json.dumps(test_records[0], indent=2))

import inspect
print(inspect.signature(failure_summary))

import json

# load preprocessed
with open("codex_s_preprocessed_test.json") as f:
    test_records = json.load(f)

# subset hard failures only
hard_failures = [
    r for r in test_records
    if r["hard_failure"]
]

print(f"Total test:      {len(test_records)}")
print(f"Hard failures:   {len(hard_failures)}")
print(f"Easy (rank 1-3): {len(test_records) - len(hard_failures)}")

# breakdown by rank
from collections import Counter
rank_counts = Counter(r["true_rank"] for r in hard_failures)
print(f"\nHard failure rank distribution:")
for rank in sorted(rank_counts):
    print(f"  rank {rank}: {rank_counts[rank]} cases")

# show what agents will receive for first hard failure
first = hard_failures[0]
print(f"\n=== FIRST HARD FAILURE — AGENT INPUT ===")
print(f"Triple:      ({first['head']}, {first['relation']}, {first['tail']})")
print(f"True rank:   {first['true_rank']}")
print(f"Predicted:   {first['predicted']}")
print(f"\nAgent context (~150 tokens):")
print(f"[sim_head]   {first['sim_head']}")
print(f"[sim_tail]   {first['sim_tail']}")
print(f"[failure]    {first['fail_summary']}")
print(f"[hop_type]   {first['hop_type']}")
print(f"\nSeparating signal (only true tail has):")
for r in first["only_tail_has"]:
    print(f"  {r}")

from sklearn.model_selection import train_test_split
import json

# load what you already generated
with open("/content/codex/codex_s_preprocessed_test.json") as f:
    test_records = json.load(f)

# split test in half — never touch held_out until final eval
val_records, held_out_records = train_test_split(
    test_records,
    test_size=0.5,
    random_state=42
)

# save separately
with open("nations_val.json", "w") as f:
    json.dump(val_records, f, indent=2)

with open("nations_held_out.json", "w") as f:
    json.dump(held_out_records, f, indent=2)

# agents only ever see val
val_hard = [r for r in val_records if r["hard_failure"]]

print(f"Val total:        {len(val_records)}")
print(f"Val hard:         {len(val_hard)}")
print(f"Held-out total:   {len(held_out_records)}")
print(f"Held-out — SEALED. Do not open until final eval.")

import json
from datetime import datetime

memory = {
    "episodic":  [],
    "semantic": {
        "agent_A": {
            "calls": 0, "successes": 0,
            "failure_patterns": []
        },
        "agent_B": {
            "calls": 0, "successes": 0,
            "separators_found": [], "dead_ends": []
        }
    },
    "graph": []  # new triples written back
}

def check_episodic(head, relation):
    """Check memory before calling LLM — avoid redundant calls."""
    for record in memory["episodic"]:
        h, r, t = record["triple"]
        if h == head and r == relation:
            return record
    return None

def add_episodic(triple, agent, finding):
    memory["episodic"].append({
        "triple":    triple,
        "agent":     agent,
        "finding":   finding,
        "timestamp": len(memory["episodic"])
    })

def add_graph_triple(head, relation, tail):
    memory["graph"].append({
        "head": head, "relation": relation, "tail": tail
    })

def update_semantic(agent, success, pattern=None):
    p = memory["semantic"][agent]
    p["calls"] += 1
    if success:
        p["successes"] += 1
    if pattern:
        p["failure_patterns"].append(pattern)

print("Memory store initialized.")
print(json.dumps(memory, indent=2))

print(val_hard[0])

def route(record):
    """
    Agent B handles all multi-hop failures — which is all test triples.
    Agent A runs as secondary check on near-misses only.
    Returns primary agent and whether to run secondary.
    """
    rank     = record["true_rank"]
    hop_type = record["hop_type"]

    # primary routing
    if hop_type == "multi" or hop_type == "none":
        primary = "B"   # path reasoning for all multi-hop
    else:
        primary = "A"   # similarity for direct edge failures

    # secondary check — run A on near misses regardless
    secondary = "A" if rank <= 6 and primary == "B" else None

    return primary, secondary

import os, csv
from collections import defaultdict

def load_tsv_memory(path=r"tsv_memory"):
    memory = defaultdict(list)

    if not os.path.exists(path):
        return memory

    with open(path) as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            h = row["head"].strip()
            r = row["relation"].strip()
            t = row["tail"].strip()

            memory[h].append((r, t))   # ← REAL triples

    return memory

def get_memory_hint(head, memory, relation=None, k=5):
    triples = memory.get(head, [])

    if not triples:
        return ""

    # prioritize same relation if provided
    if relation is not None:
        same_rel = [(r, t) for r, t in triples if r == relation]
        others   = [(r, t) for r, t in triples if r != relation]
        selected = same_rel[:k] + others[:max(0, k - len(same_rel))]
    else:
        selected = triples[:k]

    # remove duplicates while preserving order
    seen = set()
    unique = []
    for r, t in selected:
        if (r, t) not in seen:
            seen.add((r, t))
            unique.append((r, t))

    return "\n".join(
        f"{head} --{r}--> {t}" for r, t in unique
    )

tsv_memory = load_tsv_memory(r"/kaggle/input/datasets/aaryaupi/tsv-file/episodic_memory (21).tsv")
print("TSV entities:", len(tsv_memory))

total_triples = sum(len(v) for v in tsv_memory.values())

print("Unique heads:", len(tsv_memory))
print("Total triples:", total_triples)

def verify_path(path_str: str, graph: dict) -> dict:
    if not path_str or str(path_str).lower() in ["none", "null", "", "false"]:
        return {"verified": False, "reason": "no path claimed"}
    import re
    nodes = re.split(r'\s*--[^>]+-->\s*', path_str)
    rels  = re.findall(r'--(.+?)-->', path_str)
    if len(nodes) < 2 or len(rels) < 1:
        return {"verified": False, "reason": "unparseable"}
    nodes = [n.strip() for n in nodes]
    rels  = [r.strip() for r in rels]
    for src, rel, dst in zip(nodes, rels, nodes[1:]):
        edge_exists = any(r == rel and t == dst for r, t in graph.get(src, []))
        if not edge_exists:
            return {
                "verified": False,
                "reason":   f"edge ({src} --{rel}--> {dst}) not in graph",
                "nodes":    nodes, "rels": rels,
            }
    return {"verified": True, "reason": "confirmed",
            "nodes": nodes, "rels": rels, "hops": len(rels)}


def verify_relations(claimed_rels: list, head: str,
                     tail: str, df_ref: pd.DataFrame) -> dict:
    if not claimed_rels:
        return {"verified": [], "hallucinated": [], "rate": 0.0}
    actual = set(df_ref[
        (df_ref["head"] == head) & (df_ref["tail"] == tail)
    ]["relation"])
    verified     = [r for r in claimed_rels if r in actual]
    hallucinated = [r for r in claimed_rels if r not in actual]
    return {
        "verified":     verified,
        "hallucinated": hallucinated,
        "rate":         len(hallucinated) / max(len(claimed_rels), 1),
    }


def trim_subgraph(subgraph: list, head: str, true_tail: str,
                  predicted: str, only_tail_has: list,
                  max_triples: int = 12) -> list:
    """
    Rank and trim subgraph to max_triples.
    Priority:
      1. Triples containing only_tail_has relations (gold signal)
      2. Triples directly involving true_tail or predicted
      3. Triples involving head
      4. Everything else (dropped first)
    """
    tier1, tier2, tier3, tier4 = [], [], [], []
    oth_set = set(only_tail_has)

    for triple in subgraph:
        if isinstance(triple, (list, tuple)) and len(triple) == 3:
            h, r, t = triple
        elif isinstance(triple, dict):
            h, r, t = triple.get("head",""), triple.get("relation",""), triple.get("tail","")
        else:
            continue

        if r in oth_set:
            tier1.append(triple)
        elif t in (true_tail, predicted) or h in (true_tail, predicted):
            tier2.append(triple)
        elif h == head or t == head:
            tier3.append(triple)
        else:
            tier4.append(triple)

    ranked = tier1 + tier2 + tier3 + tier4
    return ranked[:max_triples]


def build_subgraph_str(record: dict, max_triples: int = 12) -> str:
    subgraph  = record.get("subgraph", [])
    true_tail = record.get("true_tail") or record.get("tail", "")
    predicted = record.get("predicted", "")
    only_tail = record.get("only_tail_has", [])

    trimmed = trim_subgraph(
        subgraph, record["head"], true_tail,
        predicted, only_tail, max_triples
    )

    if not trimmed:
        return "  (no subgraph available)"

    lines = []
    for triple in trimmed:
        if isinstance(triple, (list, tuple)) and len(triple) == 3:
            h, r, t = triple
        elif isinstance(triple, dict):
            h = triple.get("head","?")
            r = triple.get("relation","?")
            t = triple.get("tail","?")
        else:
            continue
        # mark gold signal triples visually
        marker = " ◆" if r in set(only_tail) else ""
        lines.append(f"  {h} --{r}--> {t}{marker}")

    return "\n".join(lines)


def build_agent_context(record: dict, tsv_memory=None) -> str:

    # normalise keys
    true_tail = record.get("true_tail") or record.get("tail", "")
    predicted = record.get("predicted", "unknown")
    only_tail = record.get("only_tail_has", [])
    only_pred = record.get("only_pred_has", [])

    # memory prior
    memory_block = ""
    if tsv_memory:
        hint = get_memory_hint(record["head"], tsv_memory)
        if hint:
            memory_block = f"\nMemory prior for {record['head']}:\n{hint}\n"

    # separator block — gold signal at top, impossible to miss
    if only_tail:
        separator_block = (
            f"⚠ SEPARATING RELATIONS — cite these or state you cannot:\n"
            + "\n".join(f"  ◆ {r}" for r in only_tail)
            + f"\nThese connect [{record['head']}] → [{true_tail}] "
            f"but NOT → [{predicted}].\n"
        )
    else:
        separator_block = (
            f"⚠ NO SEPARATING RELATIONS in subgraph.\n"
            f"Forbidden (connect head to WRONG entity — do not cite):\n"
            + ("\n".join(f"  ✗ {r}" for r in only_pred) or "  none")
            + "\nYou must find a multi-hop path OR output confidence 0.3.\n"
        )

    # trimmed subgraph — ◆ marks gold-signal triples
    subgraph_str = build_subgraph_str(record)

    # sim summary — trim to 3 most similar only
    sim_head = record.get("sim_head", "")
    if sim_head:
        # keep only first 3 entries to reduce noise
        parts = sim_head.split(", ")
        sim_head = ", ".join(parts[:3])

    context = f"""Triple: ({record['head']}, {record['relation']}, ?)
Predicted wrong: {predicted}  |  rank of correct answer: {record['true_rank']}

{separator_block}
{memory_block}
Subgraph (◆ = gold signal triple — use these first):
{subgraph_str}

Similarity (top-3 embedding neighbours of head):
  {sim_head}

Hop type: {record.get('hop_type','multi')}
Failure: {record.get('fail_summary','')}"""

    return context

print("build_agent_context + verifiers ready.")

import os, json, time, csv, warnings, torch
from concurrent.futures import ThreadPoolExecutor
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    BitsAndBytesConfig, pipeline as hf_pipeline,
)
warnings.filterwarnings("ignore")

MODEL_ID         = "Qwen/Qwen2.5-7B-Instruct"
AGENT_A_B_DELAY  = 10
BETWEEN_RECORDS  = 10

print(f"Loading {MODEL_ID} in 4-bit …")

_tok = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
_mdl = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
    ),
    device_map="auto",
    trust_remote_code=True,
)
_pipe = hf_pipeline(
    "text-generation",
    model=_mdl,
    tokenizer=_tok,
    do_sample=True,
    temperature=0.3,
    return_full_text=False,
)
print(f"Model ready on {_mdl.device}")


def call_llm(system: str, user: str) -> str:
    """Direct HF pipeline call. Shared by A, B, and Aggregator."""
    messages = [
        {"role": "system", "content": system},
        {"role": "user",   "content": user},
    ]
    for attempt in range(2):
        try:
            out = _pipe(messages)
            # pipeline returns list of dicts
            return out[0]["generated_text"].strip()
        except Exception as e:
            if attempt == 0:
                print(f"  [LLM] retry: {e}"); time.sleep(5)
            else:
                raise


def parse_json(raw: str, who: str) -> dict:
    text = raw.strip()
    if text.startswith("```"):
        text = "\n".join(text.split("\n")[1:-1])
    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        print(f"  [{who}] JSON parse failed: {e}\n  raw: {raw[:200]}")
        return {"error": str(e), "raw": raw}

print("Cell B ready.")

from google.colab import drive
drive.mount('/content/drive')

from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

EMBED         = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)
EPISODIC_PATH = "episodic.faiss"
SEMANTIC_PATH = "semantic.faiss"


def _load_or_create(path: str) -> FAISS:
    if os.path.exists(path):
        return FAISS.load_local(
            path, EMBED, allow_dangerous_deserialization=True
        )
    store = FAISS.from_texts(["init"], EMBED)
    store.save_local(path)
    return store


episodic_vs = _load_or_create(EPISODIC_PATH)
semantic_vs = _load_or_create(SEMANTIC_PATH)


def query_episodic(head: str, relation: str) -> str:
    docs = episodic_vs.similarity_search(f"{head} {relation}", k=2)
    hits = [d.page_content for d in docs if "init" not in d.page_content]
    return "\n".join(hits) if hits else ""


def query_semantic(failure_type: str) -> str:
    docs = semantic_vs.similarity_search(failure_type, k=2)
    hits = [d.page_content for d in docs if "init" not in d.page_content]
    return "\n".join(hits) if hits else ""


def write_episodic(head: str, relation: str, tail: str,
                   agent: str, finding: str):
    text = f"{head} {relation} → {tail} | agent {agent} | {finding}"
    episodic_vs.add_texts([text])
    episodic_vs.save_local(EPISODIC_PATH)


def write_semantic(agent: str, failure_type: str, key_rels: list):
    text = (f"agent {agent} wins on {failure_type} "
            f"| key_rels: {', '.join(key_rels)}")
    semantic_vs.add_texts([text])
    semantic_vs.save_local(SEMANTIC_PATH)

print("Cell C ready — episodic.faiss + semantic.faiss loaded.")

_A_SYS = """You are Agent A, a knowledge graph similarity
reasoning agent operating under the ReAct paradigm.

Your role: reason about which tail entity is correct using
embedding similarity profiles and shared relation patterns.
You have access to similarity scores and shared relation
counts from the KGE model.

Your inductive bias: entities that share many relations with
the head entity and appear close in embedding space are more
likely to be correct. You are fast and effective on
single-hop, similarity-resolvable failures. You are weak on
structural multi-hop cases where similar-looking entities
have different relational fingerprints.

Be explicit about when similarity evidence is weak. A high
similarity score to the wrong entity is evidence OF the
failure, not evidence of the answer.

Output ONLY valid JSON:
{
  "prediction": "<entity or null>",
  "confidence": <0.0–1.0>,
  "shared_relations": ["<rel>"],
  "failure_diagnosis": "<one sentence>",
  "evidence_type": "similarity | structural | episodic | mixed | none"
}"""

_B_SYS = """You are Agent B, a knowledge graph structural
reasoning agent operating under the ReAct paradigm.

Your role: reason about which tail entity is correct by
finding relational paths in the local subgraph. You follow
edges, verify path existence, and use only_tail_has as your
primary signal.

Your inductive bias: the correct tail entity can be reached
from the head via a path that uses the query relation or a
semantically equivalent one. Entities that share
only_tail_has relations with the head are structurally
privileged over those that do not.

HARD CONSTRAINTS:
- A path must be verifiable in the subgraph provided. Do not
  invent edges that are not shown.
- If no path exists to any candidate, set prediction to null
  and confidence to 0.05. Do not guess.
- only_tail_has relations take absolute priority over any
  other signal including episodic memory.

Output ONLY valid JSON:
{
  "prediction": "<entity or null>",
  "confidence": <0.0–1.0>,
  "key_relations": ["<rel>"],
  "path_found": "<head --rel--> tail or null>",
  "path_relation_matches_query": <true | false>,
  "reasoning": "<one sentence citing specific relations>",
  "failure_diagnosis": "<one sentence>",
  "evidence_type": "structural | episodic | mixed | none"
}"""

_USER_TMPL = """
{context}

<episodic_memory>
{episodic_hint}
</episodic_memory>

<reasoning>
STEP 1 — READ THE FAILURE SIGNAL
Identify what RotatE predicted wrongly and why. The score gap
between the true tail and the predicted tail tells you how
confidently wrong the embedding was. A large gap means the
geometry is fundamentally misleading — structural reasoning
matters more here. A small gap means the entities are close
in embedding space — similarity reasoning may still help.

STEP 2 — EXAMINE only_tail_has FIRST (PRIMARY SIGNAL)
These relations exist between the head and the TRUE tail but
NOT between the head and the predicted tail. They are the
structural fingerprint of the correct answer. Before reading
anything else, ask: does any candidate tail entity in the
subgraph have ALL of these relations with the head? If yes,
that is your answer. If multiple candidates share them, rank
by how many they share.

STEP 3 — CONSULT EPISODIC MEMORY (SECONDARY SIGNAL)
Read the past episodes. Each episode is a real triple
(head, relation, tail) that was validated as discriminative
in a previous resolved case. Ask:
  - Do any episodic triples share the head entity with this
    query? If yes, which relations from those triples also
    appear in only_tail_has for this query? Overlap here is
    strong confirmation — the same relational pattern that
    worked before is present again.
  - Do any episodic triples share the query relation? If yes,
    what tail type did they resolve to? This tells you what
    kind of entity tends to be correct for this relation.
  - If episodic memory is empty or none of the triples share
    head, relation, or relation type: IGNORE it entirely and
    proceed on structural reasoning alone. Do not confabulate
    relevance where none exists.

STEP 4 — SYNTHESISE AND COMMIT
Combine what you found in Steps 2 and 3. State your candidate
explicitly. Assign confidence based on evidence quality:
  - only_tail_has match + episodic confirmation → 0.80–0.95
  - only_tail_has match alone, clear path → 0.65–0.80
  - only_tail_has match, weak path → 0.40–0.65
  - episodic confirmation only, no structural path → 0.25–0.40
  - neither confirms, reasoning from embedding similarity → 0.10–0.30
  - no evidence at all → null, 0.05

STEP 5 — DIAGNOSE THE FAILURE
In one sentence: what specifically caused RotatE to rank the
wrong entity higher? Name the relation or structural feature
it missed.
</reasoning>

Respond with valid JSON only — no preamble, no explanation
outside the JSON:
"""

def agent_a(context: str, record: dict) -> dict:
    print(f"  [A] firing  ({record['head']}, {record['relation']}, {record['tail']})")
    hint = query_episodic(record["head"], record["relation"])
    raw  = call_llm(_A_SYS, _USER_TMPL.format(context=context, episodic_hint=hint or "none"))
    out  = parse_json(raw, "A")
    print(f"  [A] done — pred={out.get('prediction')}  conf={out.get('confidence')}")
    return out


def agent_b(context: str, record: dict) -> dict:
    print(f"  [B] firing  ({record['head']}, {record['relation']}, {record['tail']})")
    hint = query_episodic(record["head"], record["relation"])
    raw  = call_llm(_B_SYS, _USER_TMPL.format(context=context, episodic_hint=hint or "none"))
    out  = parse_json(raw, "B")
    print(f"  [B] done — pred={out.get('prediction')}  conf={out.get('confidence')}")
    return out


print("Cell D ready — agent_a() + agent_b() defined.")

def run_parallel_staggered(record: dict, tsv_memory: dict = None) -> tuple:
    context = build_agent_context(record, tsv_memory=tsv_memory)  # ← only change
    results = {}

    def _run_a():
        results["A"] = agent_a(context, record)

    def _run_b():
        time.sleep(AGENT_A_B_DELAY)
        results["B"] = agent_b(context, record)

    with ThreadPoolExecutor(max_workers=2) as ex:
        fa = ex.submit(_run_a)
        fb = ex.submit(_run_b)
        fa.result(); fb.result()

    return results["A"], results["B"]


print("Cell E ready — run_parallel_staggered() defined.")

def grounded_score(agent_out: dict, record: dict, who: str,
                   graph: dict = None,
                   df_ref: pd.DataFrame = None) -> dict:

    true_tail = record.get("true_tail") or record.get("tail", "")
    only_tail = set(record.get("only_tail_has", []))
    only_pred = set(record.get("only_pred_has", []))

    # ── strip hallucinated relations before scoring ────────
    path_verified      = None
    path_verification  = {}
    rel_verification   = {}

    if who == "B" and graph is not None:
        pv = verify_path(agent_out.get("path_found", "none"), graph)
        path_verified     = pv["verified"]
        path_verification = pv
        if not pv["verified"]:
            print(f"  [verify B] ✗ hallucinated path: {pv['reason']}")
            agent_out["path_relation_matches_query"] = False
            agent_out["path_found"]    = "none"
            agent_out["key_relations"] = []
        else:
            print(f"  [verify B] ✓ path confirmed ({pv.get('hops',1)} hops)")

    if who == "A" and df_ref is not None:
        rv = verify_relations(
            agent_out.get("shared_relations", []),
            record["head"], true_tail, df_ref
        )
        rel_verification = rv
        if rv["hallucinated"]:
            print(f"  [verify A] ✗ hallucinated rels: {rv['hallucinated']}")
            agent_out["shared_relations"] = rv["verified"]
        if rv["verified"]:
            print(f"  [verify A] ✓ confirmed rels: {rv['verified']}")

    # ── score on verified relations only ───────────────────
    agent_rels = set(
        agent_out.get("shared_relations", []) if who == "A"
        else agent_out.get("key_relations", [])
    )

    overlap_tail   = agent_rels & only_tail
    coverage_score = len(overlap_tail) / max(len(only_tail), 1)
    overlap_pred   = agent_rels & only_pred
    contamination  = len(overlap_pred) / max(len(agent_rels), 1)

    correct = (
        agent_out.get("prediction", "").strip().lower()
        == true_tail.strip().lower()
    )

    quality_score = round(
        coverage_score * (1 - 0.5 * contamination), 3
    )

    print(f"  [score {who}] coverage={coverage_score:.2f}  "
          f"contam={contamination:.2f}  quality={quality_score}  "
          f"correct={correct}")

    return {
        "agent":              who,
        "relation_score":     round(coverage_score, 3),
        "quality_score":      quality_score,
        "contamination":      round(contamination, 3),
        "overlap_tail":       sorted(overlap_tail),
        "overlap_pred":       sorted(overlap_pred),
        "agent_relations":    sorted(agent_rels),
        "only_tail_has":      sorted(only_tail),
        "prediction_correct": correct,
        "confidence":         agent_out.get("confidence", 0.0),
        "path_verified":      path_verified,
        "path_verification":  path_verification,
        "rel_verification":   rel_verification,
    }

print("grounded_score (with verification) ready.")

def get_deciding_signal(s_a: dict, s_b: dict,
                        a_out: dict, b_out: dict,
                        chosen: str, record: dict) -> str:
    qa = s_a["quality_score"]
    qb = s_b["quality_score"]
    ca = s_a["contamination"]
    cb = s_b["contamination"]

    a_cited  = len(s_a.get("agent_relations", []))
    b_cited  = len(s_b.get("agent_relations", []))
    a_rels   = s_a.get("agent_relations", [])
    b_rels   = s_b.get("agent_relations", [])
    b_path   = b_out.get("path_found", "none")
    b_match  = b_out.get("path_relation_matches_query", False)
    hop      = record.get("hop_type", "multi")

    if chosen == "A":
        # rule 1 — quality gap
        if qa > 0.5 and qb <= 0.5:
            return (f"Agent A quality ({qa:.2f}) exceeded threshold, "
                    f"Agent B quality ({qb:.2f}) did not — "
                    f"A cited {a_rels} with contamination {ca:.2f}")
        # rule 2 — contamination
        if ca < cb:
            overlap = s_a.get("overlap_tail", [])
            noise   = s_a.get("overlap_pred", [])
            return (f"Agent A contamination ({ca:.2f}) lower than "
                    f"B ({cb:.2f}) — A cited only discriminating "
                    f"relations {overlap}, "
                    f"no prediction-entity noise "
                    f"vs B which introduced {s_b.get('overlap_pred', [])}")
        # rule 3 — single hop default
        return (f"Quality equal (A={qa:.2f} B={qb:.2f}), "
                f"contamination equal (A={ca:.2f} B={cb:.2f}), "
                f"single-hop query favours similarity agent — "
                f"A cited {a_rels}")

    else:  # chosen == B
        # rule 1 — quality gap
        if qb > 0.5 and qa <= 0.5:
            overlap = s_b.get("overlap_tail", [])
            return (f"Agent B quality ({qb:.2f}) exceeded threshold, "
                    f"Agent A quality ({qa:.2f}) did not — "
                    f"B identified discriminating relations {overlap}")
        # rule 2 — contamination
        if cb < ca:
            return (f"Agent B contamination ({cb:.2f}) lower than "
                    f"A ({ca:.2f}) — B path {b_path} cited "
                    f"more precise relations {b_rels}")
        # rule 3 — multi-hop default with context
        path_str = (f"path {b_path} found"
                    if b_path not in ["none", "null", None, ""]
                    else "no explicit path but")
        return (f"Quality equal (A={qa:.2f} B={qb:.2f}), "
                f"contamination equal (A={ca:.2f} B={cb:.2f}), "
                f"multi-hop query — B {path_str}, "
                f"cited {b_cited} relations {b_rels} "
                f"vs A cited {a_cited} relations {a_rels}, "
                f"path_relation_matches_query={b_match}")

_AGG_SYS = """You are documenting a Knowledge Graph routing decision.
The routing decision has already been made by a deterministic scorer.

Your job is ONLY to:
1. Write one sentence explaining WHY the chosen agent was trusted
   - Use the deciding signal as INPUT to your reasoning
   - Write a natural, informative sentence — do not copy the signal verbatim
   - Mention specific relations, scores, or path evidence where available
   - Example good reason: "Agent B cited commonbloc2 as the sole
     discriminating relation with zero contamination, while Agent A
     introduced path noise through commonbloc0"
   - Example bad reason: "Agent B preferred on multi-hop query"
2. Classify the failure type

Output ONLY valid JSON, no other text:
{
  "reason": "<one specific, informative sentence>",
  "failure_type": "similarity_confusion | structural_gap | both_failed | resolved"
}"""

_AGG_USER = """Triple: ({head}, {relation}, ?)
Hop type: {hop_type}
Chosen agent: {chosen}
Deciding signal: {deciding_signal}

Agent A:
  prediction:        {a_pred}
  confidence:        {a_conf}
  shared_relations:  {a_relations}  [cited {a_cited} relations]
  failure_diagnosis: {a_diagnosis}

Agent B:
  prediction:                  {b_pred}
  confidence:                  {b_conf}
  key_relations:               {b_relations}  [cited {b_cited} relations]
  path_found:                  {b_path}
  path_relation_matches_query: {b_rel_match}
  reasoning:                   {b_reasoning}
  failure_diagnosis:           {b_diagnosis}

If the chosen agent used a path:
- explicitly mention whether the path matched the query relation
Write ONE sentence explaining why Agent {chosen} was trusted
based on the deciding signal above.
Do not argue for the other agent.
Do not mention the correct answer."""

def _python_route(s_a: dict, s_b: dict, record: dict) -> str:
    """
    Deterministic routing — uses quality_score and contamination.
    Legitimate in training phase — scorer has true_tail.
    """
    qa = s_a["quality_score"]
    qb = s_b["quality_score"]
    ca = s_a["contamination"]
    cb = s_b["contamination"]

    # rule 1 — clear quality gap
    if qa > 0.5 and qb <= 0.5:
        return "A"
    if qb > 0.5 and qa <= 0.5:
        return "B"

    # rule 2 — both have quality, pick lower contamination
    if qa > 0 and qb > 0:
        if ca < cb:
            return "A"
        if cb < ca:
            return "B"

    # rule 3 — quality equal, use hop type preference
    if record["hop_type"] != "single":
        return "B"
    return "A"

def aggregate(a_out: dict, b_out: dict,
              s_a: dict, s_b: dict,
              record: dict) -> dict:

    # ── step 1: deterministic routing ─────────────────────
    chosen       = _python_route(s_a, s_b, record)
    chosen_out   = a_out if chosen == "A" else b_out
    chosen_score = s_a   if chosen == "A" else s_b

    final_answer    = chosen_out.get("prediction", "")
    deciding_signal = get_deciding_signal(s_a, s_b, a_out, b_out, chosen, record)

    print(f"  [Route] Python chose agent {chosen} "
          f"(quality={chosen_score['quality_score']} "
          f"contam={chosen_score['contamination']})")
    print(f"  [Route] signal: {deciding_signal}")

    # ── step 2: LLM documents reason + failure_type ───────
    print("  [Agg] LLM labelling ...")
    user = _AGG_USER.format(
        head            = record["head"],
        relation        = record["relation"],
        hop_type        = record["hop_type"],
        chosen          = chosen,
        deciding_signal = deciding_signal,

        # Agent A
        a_pred      = a_out.get("prediction",       "unknown"),
        a_conf      = a_out.get("confidence",        0.0),
        a_relations = a_out.get("shared_relations",  []),
        a_cited     = len(s_a.get("agent_relations", [])),
        a_diagnosis = a_out.get("failure_diagnosis", "none"),

        # Agent B
        b_pred      = b_out.get("prediction",                  "unknown"),
        b_conf      = b_out.get("confidence",                   0.0),
        b_relations = b_out.get("key_relations",                []),
        b_cited     = len(s_b.get("agent_relations",            [])),
        b_path      = b_out.get("path_found",                  "none"),
        b_rel_match = b_out.get("path_relation_matches_query",  False),
        b_reasoning = b_out.get("reasoning",                   "none"),
        b_diagnosis = b_out.get("failure_diagnosis",           "none"),
    )

    raw     = call_llm(_AGG_SYS, user)
    llm_out = parse_json(raw, "Agg")

    out = {
        "final_answer":       final_answer,
        "chosen_agent":       chosen,
        "confidence":         chosen_out.get("confidence", 0.0),
        "reason":             llm_out.get("reason",       ""),
        "selected_relations": chosen_score.get("overlap_tail", []),
        "failure_type":       llm_out.get("failure_type", "resolved"),
    }

    print(f"  [Agg] done — final={out['final_answer']}  "
          f"agent={out['chosen_agent']}  "
          f"type={out['failure_type']}")
    return out

EPISODIC_TSV = "episodic_memory.tsv"

def extract_reasoning_patterns(record: dict, agg: dict) -> list[tuple]:
    """
    Extract reusable relational patterns from a resolved case.

    Instead of storing the answer, we store:
    (head, discriminative_relation, correct_tail)

    These are actual KG-grounded triples that encode WHY the
    correct tail was chosen — the separating signal — not just
    what was chosen.

    Only patterns grounded in only_tail_has are stored,
    because those are the relations that structurally separate
    the true tail from the predicted (wrong) entity.
    """
    patterns = []

    head        = record["head"]
    true_tail   = record["tail"]
    only_tail   = set(record.get("only_tail_has", []))
    selected    = set(agg.get("selected_relations", []))
    subgraph    = record.get("subgraph", [])

    # only relations that are BOTH:
    # 1. cited by the winning agent as discriminative
    # 2. actually exist in the subgraph as a real triple
    # 3. are separating signals (in only_tail_has)
    grounded_discriminative = selected & only_tail

    # build a lookup of what triples actually exist in subgraph
    subgraph_triples = {(h, r, t) for h, r, t in subgraph}

    for rel in grounded_discriminative:
        # verify this triple actually exists in the local graph
        # — prevents storing hallucinated relations
        if (head, rel, true_tail) in subgraph_triples:
            patterns.append((head, rel, true_tail))
        else:
            # try the reverse — maybe it's a tail→head edge
            if (true_tail, rel, head) in subgraph_triples:
                patterns.append((true_tail, rel, head))

    return patterns


def writeback(agg: dict, record: dict):
    """
    Quality-gated writeback that stores only:
    - Resolved cases (agent got it right)
    - Relations that are both agent-cited AND structurally
      discriminative (in only_tail_has)
    - Triples that actually exist in the local subgraph
      (grounded, not hallucinated)

    Result: episodic memory contains real KG triples that
    encode discriminative relational patterns, not meta-logs.
    """
    # gate 1 — only store resolved cases
    if agg.get("failure_type") != "resolved":
        return
    if agg.get("final_answer") != record.get("tail"):
        return

    # gate 2 — extract grounded patterns
    patterns = extract_reasoning_patterns(record, agg)

    if not patterns:
        # agent got it right but cited no discriminative
        # subgraph-grounded relations → lucky prediction
        # do NOT store — this is exactly the noise you want
        # to exclude
        print(f"  [TSV] skipped — lucky prediction, "
              f"no grounded discriminative relations")
        return

    # write clean triples
    new_file = not os.path.exists(EPISODIC_TSV)
    with open(EPISODIC_TSV, "a", newline="") as f:
        w = csv.writer(f, delimiter="\t")
        if new_file:
            w.writerow(["head", "relation", "tail"])
        w.writerows(patterns)

    print(f"  [TSV] {len(patterns)} grounded triples → "
          f"{EPISODIC_TSV}")

    # FAISS episodic — store the pattern as retrievable text
    # format: "head --rel--> tail" for semantic search
    for h, r, t in patterns:
        write_episodic(
            h, r, t,
            agg.get("chosen_agent", "?"),
            f"discriminative: {h} --{r}--> {t}"
        )

    # FAISS semantic — store relation-level pattern
    # for cross-entity generalisation
    write_semantic(
        agg.get("chosen_agent", "?"),
        record.get("relation", "?"),   # query relation
        list({r for _, r, _ in patterns})
    )

def run_pipeline(record: dict, tsv_memory: dict = None,
                 graph: dict = None,
                 df_ref: pd.DataFrame = None) -> dict:

    # normalise keys
    if "true_tail" not in record:
        record["true_tail"] = record.get("tail", "")
    if "hop_type" not in record:
        record["hop_type"] = "multi"

    t = (f"({record['head']}, {record['relation']}, "
         f"{record['true_tail']})")
    print(f"\n{'='*55}\nPIPELINE  {t}\n"
          f"rank={record['true_rank']}  hop={record['hop_type']}\n"
          f"{'='*55}")

    a_out, b_out = run_parallel_staggered(record, tsv_memory=tsv_memory)

    # pass graph + df_ref for deterministic verification
    s_a = grounded_score(a_out, record, "A",
                         graph=graph, df_ref=df_ref)
    s_b = grounded_score(b_out, record, "B",
                         graph=graph, df_ref=df_ref)

    agg = aggregate(a_out, b_out, s_a, s_b, record)
    writeback(agg, record)

    correct = (
        agg.get("final_answer","").strip().lower()
        == record["true_tail"].strip().lower()
    )
    print(f"\n{'✓' if correct else '✗'}  "
          f"final={agg.get('final_answer')}  "
          f"agent={agg.get('chosen_agent')}")

    return {
        "triple":        t,
        "true_tail":     record["true_tail"],
        "hop_type":      record["hop_type"],
        "model_rank":    record["true_rank"],
        "agent_a":       a_out,
        "agent_b":       b_out,
        "score_a":       s_a,
        "score_b":       s_b,
        "aggregator":    agg,
        "final_correct": correct,
    }

print("run_pipeline (with verification) ready.")

import json, os, time

AGENT_A_B_DELAY  = 10   # override the Cell B values for this run
BETWEEN_RECORDS  = 10
CHECKPOINT_FILE  = "val_hard_checkpoint.json"
RESULTS_FILE     = "val_hard_results1.json"


# ── checkpoint helpers ────────────────────────────────────

def load_checkpoint() -> dict:
    """Returns {triple_key: result} for all completed records."""
    if os.path.exists(CHECKPOINT_FILE):
        with open(CHECKPOINT_FILE) as f:
            return json.load(f)
    return {}


def save_checkpoint(checkpoint: dict):
    with open(CHECKPOINT_FILE, "w") as f:
        json.dump(checkpoint, f, indent=2)


def triple_key(record: dict) -> str:
    return f"{record['head']}|{record['relation']}|{record['tail']}"


# ── load checkpoint — skip already done ──────────────────

checkpoint   = load_checkpoint()
already_done = set(checkpoint.keys())
remaining    = [r for r in val_hard if triple_key(r) not in already_done]

print(f"val_hard total:    {len(val_hard)}")
print(f"Already completed: {len(already_done)}")
print(f"Remaining:         {len(remaining)}")
if already_done:
    print(f"Resuming from checkpoint: {CHECKPOINT_FILE}")

# ── main loop ────────────────────────────────────────────

all_results = list(checkpoint.values())   # start with completed ones

for i, record in enumerate(remaining):
    key = triple_key(record)
    print(f"\n[{i+1}/{len(remaining)}]  {key}  rank={record['true_rank']}")

    try:
        result = run_pipeline(record , tsv_memory = None , graph = graph , df_ref = df_train)
        checkpoint[key] = result
        all_results.append(result)
        save_checkpoint(checkpoint)           # persist after every record

    except Exception as e:
        print(f"  [ERROR] {key} failed: {e}")
        print(f"  Skipping — will retry on next run.")
        checkpoint[key] = {"error": str(e), "triple": key}
        save_checkpoint(checkpoint)

    if i < len(remaining) - 1:
        time.sleep(BETWEEN_RECORDS)


# ── save full results ─────────────────────────────────────

clean_results = [r for r in all_results if "error" not in r]
with open(RESULTS_FILE, "w") as f:
    json.dump(clean_results, f, indent=2)


# ── summary ──────────────────────────────────────────────

errors  = [r for r in all_results if "error" in r]
correct = [r for r in clean_results if r.get("final_correct")]
agents  = [r["aggregator"].get("chosen_agent") for r in clean_results]
ftypes  = [r["aggregator"].get("failure_type")  for r in clean_results]

from collections import Counter

print(f"\n{'='*55}  FINAL SUMMARY")
print(f"Total processed:  {len(all_results)}")
print(f"Errors/skipped:   {len(errors)}")
print(f"Clean results:    {len(clean_results)}")
print(f"Correct:          {len(correct)} / {len(clean_results)}"
      f"  ({100*len(correct)/max(len(clean_results),1):.1f}%)")
print(f"\nAgent chosen breakdown:")
for agent, count in Counter(agents).most_common():
    print(f"  Agent {agent}: {count}")
print(f"\nFailure type breakdown:")
for ftype, count in Counter(ftypes).most_common():
    print(f"  {ftype}: {count}")
print(f"\nFiles written:")
print(f"  {CHECKPOINT_FILE}  (checkpoint — safe to delete after XGBoost)")
print(f"  {RESULTS_FILE}")
print(f"  {EPISODIC_TSV}")
print(f"  {EPISODIC_PATH}/  {SEMANTIC_PATH}/")

import json

with open("val_hard_results1.json") as f:
    results = json.load(f)

# categorize safely
resolved = [r for r in results if r.get("failure_type") == "resolved"]
structural = [r for r in results if r.get("failure_type") == "structural_gap"]
both_failed = [r for r in results if r.get("failure_type") == "both_failed"]

print(f"Total: {len(results)}")
print(f"Resolved: {len(resolved)}")
print(f"Structural gap: {len(structural)}")
print(f"Both failed: {len(both_failed)}")

# helper to avoid IndexError
def print_example(lst, name):
    print(f"\n=== ONE {name.upper()} CASE ===")
    if lst:
        print(json.dumps(lst[0], indent=2))
    else:
        print(f"No {name} cases found.")

print_example(resolved, "resolved")
print_example(structural, "structural gap")
print_example(both_failed, "both_failed")

# find and fix the mislabeled entry
for r in results:
    if r.get("agent_used") == "Agent Agent A":
        print("Found mislabeled entry:")
        print(json.dumps(r, indent=2))
        r["agent_used"] = "A"  # fix in memory

# resave
with open("val_hard_results.json", "w") as f:
    json.dump(results, f, indent=2)

print("Fixed.")

_AGG_USER_INFER = """
Triple: ({head}, {relation}, ?)
Hop type: {hop_type}

Chosen agent: {chosen}

Deciding signal:
{deciding_signal}

Agent A:
  prediction:        {a_pred}
  confidence:        {a_conf}
  shared_relations:  {a_relations}  [cited {a_cited} relations]
  failure_diagnosis: {a_diagnosis}

Agent B:
  prediction:                  {b_pred}
  confidence:                  {b_conf}
  key_relations:               {b_relations}  [cited {b_cited} relations]
  path_found:                  {b_path}
  path_relation_matches_query: {b_rel_match}
  reasoning:                   {b_reasoning}
  failure_diagnosis:           {b_diagnosis}

Both agents predict the same entity: {both_agree}

Write ONE sentence explaining why Agent {chosen} was trusted.
Use relations and paths only — no numeric scores.
Do not mention correctness.
"""

_AGG_SYS_INFER = """
You are documenting a Knowledge Graph routing decision.
The routing decision has already been made by a deterministic scorer.

IMPORTANT:
- You DO NOT know the correct answer
- You MUST NOT guess correctness
- You MUST NOT use labels like "resolved" or "both_failed"

Instead, evaluate the STRUCTURAL QUALITY of reasoning.

Structural assessment definitions:

- strong_path:
  A clear path exists and the relation closely matches the query

- weak_path:
  A path exists but uses indirect or loosely related relations

- no_path:
  No valid path or relation evidence exists

- conflicting_signals:
  Multiple competing relations/entities create ambiguity

STRICT RULES:
1. Use ONLY:
     • relations
     • paths
     • citation counts
2. DO NOT mention:
     • correctness
     • quality_score
     • contamination
     • numeric scores
3. Prefer "strong_path" ONLY if:
     • path_verified = true AND
     • relation matches query
4. If path is hallucinated or missing → NOT strong_path
5. If both agents provide weak signals → use "conflicting_signals"

Your job is ONLY to:

1. Write ONE sentence explaining WHY the chosen agent was trusted
2. Assign structural_assessment

Output ONLY valid JSON:
{
  "reason": "<one sentence using relations/paths only>",
  "structural_assessment": "strong_path | weak_path | no_path | conflicting_signals"
}
"""

def inference_deciding_signal(s_a: dict, s_b: dict,
                               a_out: dict, b_out: dict,
                               chosen: str, record: dict) -> str:
    """
    Clean deciding signal for inference.
    Uses only cited_count, path_found, rel_match, confidence.
    No quality_score, no contamination, no true_tail.
    """
    a_cited     = s_a.get("cited_count", 0)
    b_cited     = s_b.get("cited_count", 0)
    a_conf      = s_a.get("confidence",  0.0)
    b_conf      = s_b.get("confidence",  0.0)
    b_path      = s_b.get("path_found",  False)
    b_rel_match = s_b.get("rel_match",   False)
    a_rels      = s_a.get("agent_relations", [])
    b_rels      = s_b.get("agent_relations", [])
    b_path_str  = b_out.get("path_found", "none")

    if chosen == "B":
        # rule 1 — path + rel_match, check if conf is low
        if b_path and b_rel_match:
            conf_note = (f", note: B confidence low ({b_conf}) "
                        f"vs A confidence ({a_conf})"
                        if b_conf < 0.5 else "")
            return (f"Agent B found path {b_path_str} "
                    f"with path_relation_matches_query=True — "
                    f"B cited {b_cited} relations {b_rels}, "
                    f"A cited {a_cited} relations {a_rels}"
                    f"{conf_note}")

        # rule 2 — path but no rel_match
        if b_path and not b_rel_match:
            return (f"Agent B found path {b_path_str} "
                    f"and cited {b_cited} relations {b_rels} "
                    f"vs Agent A citing {a_cited} relations {a_rels}, "
                    f"path relation does not exactly match query relation")

        # rule 4 — more citations
        if b_cited > a_cited:
            return (f"No path found — Agent B cited more relations "
                    f"({b_cited}: {b_rels}) vs Agent A "
                    f"({a_cited}: {a_rels})")

        # rule 5 — multi-hop default
        return (f"Confidence equal (A={a_conf} B={b_conf}), "
                f"citations equal (A={a_cited} B={b_cited}), "
                f"multi-hop query defaults to Agent B — "
                f"B relations: {b_rels} vs A relations: {a_rels}")

    else:  # chosen == A
        # rule 1b — B had path+match but low confidence, A higher conf
        if b_path and b_rel_match and a_conf > b_conf:
            return (f"Agent B found path {b_path_str} with rel_match=True "
                    f"but low confidence ({b_conf}) — "
                    f"Agent A confidence ({a_conf}) higher, "
                    f"A cited {a_rels}")

        # rule 3 — higher confidence
        if a_conf > b_conf:
            return (f"Agent A confidence ({a_conf}) higher than "
                    f"B ({b_conf}) — A cited {a_cited} "
                    f"relations {a_rels}")

        # rule 4 — more citations
        if a_cited > b_cited:
            return (f"No path found — Agent A cited more relations "
                    f"({a_cited}: {a_rels}) vs Agent B "
                    f"({b_cited}: {b_rels})")

        # single hop default
        return (f"Single-hop query defaults to Agent A — "
                f"A relations: {a_rels} vs B relations: {b_rels}")


def inference_score(agent_out: dict, who: str,
                    graph: dict = None) -> dict:

    # ── strip hallucinated paths before scoring ────────────
    path_verified = None
    if who == "B" and graph is not None:
        pv = verify_path(agent_out.get("path_found", "none"), graph)
        path_verified = pv["verified"]
        if not pv["verified"]:
            print(f"  [infer-verify B] ✗ {pv['reason']}")
            agent_out["path_relation_matches_query"] = False
            agent_out["path_found"]    = "none"
            agent_out["key_relations"] = []
        else:
            print(f"  [infer-verify B] ✓ confirmed")

    agent_rels  = set(
        agent_out.get("shared_relations", []) if who == "A"
        else agent_out.get("key_relations", [])
    )
    b_path      = str(agent_out.get("path_found","none")).lower() \
                  not in ["none","null","","false"]
    b_rel_match = bool(agent_out.get("path_relation_matches_query", False))
    confidence  = float(agent_out.get("confidence", 0.0))
    cited_count = len(agent_rels)

    print(f"  [infer-score {who}] cited={cited_count}  "
          f"path={b_path}  rel_match={b_rel_match}  "
          f"conf={confidence}  path_verified={path_verified}")

    return {
        "agent":              who,
        "relation_score":     None,
        "quality_score":      None,
        "contamination":      None,
        "overlap_tail":       [],
        "overlap_pred":       [],
        "agent_relations":    sorted(agent_rels),
        "only_tail_has":      [],
        "prediction_correct": None,
        "confidence":         confidence,
        "cited_count":        cited_count,
        "path_found":         b_path,
        "rel_match":          b_rel_match,
        "path_verified":      path_verified,
    }

print("inference_score (with verification) ready.")


def inference_route(s_a: dict, s_b: dict, record: dict) -> str:
    """
    Inference-phase router.
    No quality_score, no contamination — clean signals only.
    Confidence threshold added to rule 1 — path+match ignored
    if B confidence is low and A confidence is higher.
    """
    a_cited     = s_a.get("cited_count", 0)
    b_cited     = s_b.get("cited_count", 0)
    a_conf      = s_a.get("confidence",  0.0)
    b_conf      = s_b.get("confidence",  0.0)
    b_path      = s_b.get("path_found",  False)
    b_rel_match = s_b.get("rel_match",   False)

    # rule 1 — B found path + rel_match + reasonable confidence
    if b_path and b_rel_match and b_conf >= 0.5:
        return "B"

    # rule 1b — B has path+match but low confidence
    # defer to confidence comparison
    if b_path and b_rel_match and b_conf < 0.5:
        if a_conf > b_conf:
            return "A"
        return "B"  # B still wins if A equally uncertain

    # rule 2 — B found path but relation doesn't match
    if b_path and not b_rel_match:
        return "B" if b_cited >= a_cited else "A"

    # rule 3 — no path → confidence decides
    if a_conf > b_conf:
        return "A"

    # rule 4 — confidence equal → citations decide
    if b_cited > a_cited:
        return "B"

    # rule 5 — everything equal → multi-hop default
    if record.get("hop_type", "multi") != "single":
        return "B"

    return "A"


def inference_aggregate(a_out: dict, b_out: dict,
                        s_a: dict, s_b: dict,
                        record: dict) -> dict:
    """
    Inference-phase aggregator.
    Routes using clean signals only.
    LLM labels reason and failure_type without seeing true_tail.
    """
    chosen     = inference_route(s_a, s_b, record)
    chosen_out = a_out if chosen == "A" else b_out
    chosen_s   = s_a   if chosen == "A" else s_b

    final_answer    = chosen_out.get("prediction", "")
    deciding_signal = inference_deciding_signal(
        s_a, s_b, a_out, b_out, chosen, record
    )

    # flag for LLM — helps it classify both_failed correctly
    both_agree = (
        a_out.get("prediction", "").strip().lower() ==
        b_out.get("prediction", "").strip().lower()
    )

    print(f"  [infer-route] chose agent {chosen} "
          f"(cited={chosen_s['cited_count']} "
          f"path={s_b['path_found']} "
          f"rel_match={s_b['rel_match']} "
          f"b_conf={s_b['confidence']})")
    print(f"  [infer-route] signal: {deciding_signal}")
    print(f"  [infer-route] both_agree={both_agree}")

    print("  [infer-agg] LLM labelling ...")
    user = _AGG_USER_INFER.format(
        head            = record["head"],
        relation        = record["relation"],
        hop_type        = record.get("hop_type", "multi"),
        chosen          = chosen,
        deciding_signal = deciding_signal,
        both_agree      = both_agree,

        # Agent A
        a_pred      = a_out.get("prediction",       "unknown"),
        a_conf      = a_out.get("confidence",        0.0),
        a_relations = a_out.get("shared_relations",  []),
        a_cited     = s_a.get("cited_count",         0),
        a_diagnosis = a_out.get("failure_diagnosis", "none"),

        # Agent B
        b_pred      = b_out.get("prediction",                  "unknown"),
        b_conf      = b_out.get("confidence",                   0.0),
        b_relations = b_out.get("key_relations",                []),
        b_cited     = s_b.get("cited_count",                    0),
        b_path      = b_out.get("path_found",                  "none"),
        b_rel_match = b_out.get("path_relation_matches_query",  False),
        b_reasoning = b_out.get("reasoning",                   "none"),
        b_diagnosis = b_out.get("failure_diagnosis",           "none"),
    )

    raw     = call_llm(_AGG_SYS_INFER, user)
    llm_out = parse_json(raw, "InferAgg")

    out = {
        "final_answer":       final_answer,
        "chosen_agent":       chosen,
        "confidence":         chosen_out.get("confidence", 0.0),
        "reason":             llm_out.get("reason",       ""),
        "selected_relations": chosen_s.get("agent_relations", []),
        "failure_type":       llm_out.get("failure_type", "resolved"),
    }

    print(f"  [infer-agg] done — final={out['final_answer']}  "
          f"agent={out['chosen_agent']}  "
          f"type={out['failure_type']}")
    return out

# ════════════════════════════════════════════════════════
# CELL O — run pipeline on held_out hard failures (INFERENCE MODE)
# Uses inference_score, inference_aggregate — no true_tail in loop
# ════════════════════════════════════════════════════════
import json, os, time

HELD_OUT_CHECKPOINT = "held_out_checkpoint.json"
HELD_OUT_RESULTS    = "held_out_results.json"

# ── load held_out_records ─────────────────────────────────
with open("nations_held_out.json") as f:
    held_out_records = json.load(f)

# ── find hard failures ────────────────────────────────────
held_hard = [r for r in held_out_records if r["hard_failure"]]
print(f"Held-out total:       {len(held_out_records)}")
print(f"Hard failures (>3):   {len(held_hard)}")

# ── load checkpoint if exists ─────────────────────────────
def load_checkpoint_file(path):
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return {}

held_checkpoint   = load_checkpoint_file(HELD_OUT_CHECKPOINT)
held_already_done = set(held_checkpoint.keys())
held_remaining    = [
    r for r in held_hard
    if triple_key(r) not in held_already_done
]

print(f"Already done:         {len(held_already_done)}")
print(f"Remaining:            {len(held_remaining)}")

# ── load TSV memory from training writeback ───────────────
tsv_memory = load_tsv_memory("/kaggle/input/datasets/aaryaupi/tsv-file/episodic_memory (21).tsv")
print(f"TSV memory loaded:    {len(tsv_memory)} entities")

held_all_results = list(held_checkpoint.values())

# ── run pipeline ──────────────────────────────────────────
for i, record in enumerate(held_remaining):
    key = triple_key(record)
    print(f"\n[{i+1}/{len(held_remaining)}]  {key}  rank={record['true_rank']}")

    try:
        context = build_agent_context(record, tsv_memory=tsv_memory)  # ← CHANGED

        results = {}
        def _run_a():
            results["A"] = agent_a(context, record)
        def _run_b():
            time.sleep(AGENT_A_B_DELAY)
            results["B"] = agent_b(context, record)

        with ThreadPoolExecutor(max_workers=2) as ex:
            fa = ex.submit(_run_a)
            fb = ex.submit(_run_b)
            fa.result(); fb.result()

        a_out, b_out = results["A"], results["B"]

        # ── inference scoring — no true_tail, no record passed ──
        s_a = inference_score(a_out, "A",graph = graph)
        s_b = inference_score(b_out, "B", graph = graph )

        # ── inference aggregation — clean routing + LLM labelling ──
        agg = inference_aggregate(a_out, b_out, s_a, s_b, record)

        # ── correctness checked post-hoc only, never fed back in ──
        correct = (
            agg.get("final_answer", "").strip().lower()
            == record["tail"].strip().lower()
        )

        result = {
            "triple":        key,
            "true_tail":     record["tail"],
            "model_rank":    record["true_rank"],
            "agent_a":       a_out,
            "agent_b":       b_out,
            "score_a":       s_a,
            "score_b":       s_b,
            "aggregator":    agg,
            "final_correct": correct,
        }

        held_checkpoint[key] = result
        held_all_results.append(result)
        with open(HELD_OUT_CHECKPOINT, "w") as f:
            json.dump(held_checkpoint, f, indent=2)

    except Exception as e:
        print(f"  [ERROR] {key}: {e}")
        held_checkpoint[key] = {"error": str(e), "triple": key}
        with open(HELD_OUT_CHECKPOINT, "w") as f:
            json.dump(held_checkpoint, f, indent=2)

    if i < len(held_remaining) - 1:
        time.sleep(BETWEEN_RECORDS)

# ── save clean results ────────────────────────────────────
held_clean = [
    r for r in held_all_results
    if isinstance(r, dict)
    and "error" not in r
    and "score_a" in r
]

with open(HELD_OUT_RESULTS, "w") as f:
    json.dump(held_clean, f, indent=2)

held_correct = sum(1 for r in held_clean if r.get("final_correct"))
print(f"\n{'='*45}  HELD-OUT SUMMARY")
print(f"Processed:    {len(held_clean)}")
print(f"Correct:      {held_correct}/{len(held_clean)}"
      f"  ({100*held_correct/max(len(held_clean),1):.1f}%)")
print(f"\nSaved: {HELD_OUT_RESULTS}")